global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using PortsAndAdapters_And_CleanArchitecture.Domain.Models;
global using PortsAndAdapters_And_CleanArchitecture.Domain.Services;
global using PortsAndAdapters_And_CleanArchitecture.Infra.Data;
global using PortsAndAdapters_And_CleanArchitecture.Infra.EntityFramework;
global using PortsAndAdapters_And_CleanArchitecture.Application;