// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PortsAndAdapters_And_CleanArchitecture.Infra.EntityFramework;

#nullable disable

namespace PortsAndAdaptersAndCleanArchitecture.Migrations
{
    [DbContext(typeof(EfSqliteAdapter))]
    partial class EfSqliteAdapterModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("PortsAndAdapters_And_CleanArchitecture.Models.Conta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Saldo")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });
#pragma warning restore 612, 618
        }
    }
}
